#!/usr/bin/env php
<?php

define("CMS_ROOT", dirname(__FILE__));    
putenv("myEnv=CLI");

require_once(CMS_ROOT.'/Framework/Classes/Bootstrap/Bootstrap.php');

Bootstrap::getInstance()
	->injectConfig(CMS_ROOT."/Framework/Meta/config.php")
	->startMvc();

?>
