<?php
/* 
* This file will soon be auto-generated by the Bootstrapper.
**/

return array(   
	"classes"	=> array(
		"Mvc"	=>	array(
			"Dispatcher"	=>	array(
				"name"	=>	"Dispatcher",
				"file"	=>	CMS_ROOT."/Fr"
			),
		),
	),
	
	"classes"	=> array(
		"Dispatcher"	=>	array(
			"name"	=>	"Dispatcher",
			"file"	=>	CMS_ROOT."/Framework/Classes/Mvc/Dispatcher.php",
			"singleton"	=>	"true",	
		),  
		"AbstractPageController"	=>	array(
			"name"	=>	"AbstractPageController",
			"file"	=>	CMS_ROOT."/Framework/Classes/Mvc/Abstract/AbstractPageController.php",
			"abstract"	=>	"true",	
		),      
		"PageControllerInterface"	=>	array(
			"name"	=>	"PageControllerInterface",
			"file"	=>	CMS_ROOT."/Framework/Classes/Mvc/Abstract/PageControllerInterface.php",
			"interface"	=>	"true",	
		),		
		"Request"	=>	array(
			"name"	=>	"Request",
			"file"	=>	CMS_ROOT."/Framework/Classes/Mvc/Request.php",
		), 
		"Response"	=>	array(
			"name"	=>	"Response",
			"file"	=>	CMS_ROOT."/Framework/Classes/Mvc/Response.php",
			"singleton"	=>	"true",	
		),     
		"Route"	=>	array(
			"name"	=>	"Route",
			"file"	=>	CMS_ROOT."/Framework/Classes/Mvc/Routing/Route.php",
		),   
		"Router"	=>	array(
			"name"	=>	"Router",
			"file"	=>	CMS_ROOT."/Framework/Classes/Mvc/Routing/Router.php",  
			"singleton"	=>	"true",	
		),              
		"View"	=>	array(
			"name"	=>	"View",
			"file"	=>	CMS_ROOT."/Framework/Classes/Mvc/View/View.php",  
		),   
		"AbstractRenderer"	=>	array(
			"name"	=>	"AbstractRenderer",
			"file"	=>	CMS_ROOT."/Framework/Classes/Mvc/View/Renderer/Abstract/AbstractRenderer.php", 
			"abstract"	=>	"true", 
		),
		"Config"	=>	array(
			"name"	=>	"Config",
			"file"	=>	CMS_ROOT."/Framework/Classes/Utility/Config.php",  
			"singleton"	=>	"true",	
		),    
		"RenderingObjectInterface"	=>	array(
			"name"	=>	"RenderingObjectInterface",
			"file"	=>	CMS_ROOT."/Framework/Classes/Mvc/View/Renderer/Abstract/RenderingObjectInterface.php",  
		),     
		"XSLTRenderer"	=>	array(
			"name"	=>	"XSLTRenderer",
			"file"	=>	CMS_ROOT."/Framework/Classes/Mvc/View/Renderer/XSLTRenderer.php",  
		),
	),
	"defaultRoute"	=>	array(
		"module"		=>	"standard",
		"controller"	=>	"index",
		"action"		=>	"index",
	),
	"modules"	=>	array(
		"standard"	=>	array(
			"name"	=>	"standard",
			"allowOverwriteRoutes"	=>	true,      
			"config"	=>	array(
				"file"	=>	CMS_ROOT."/Modules/standard/config.php"
			),
			"classes" =>	array( 
				"ErrorController"	=> array(
					"name"	=>	"ErrorController",
					"file"	=>	CMS_ROOT."/Modules/standard/controllers/ErrorController.php"
				),
				"IndexController"	=>	array(
					"name"	=>	"IndexController",
					"file"	=>	CMS_ROOT."/Modules/standard/controllers/IndexController.php"
				)
			),
		),                                  
		 "blog"	=>	array(
			"name"	=>	"blog",
			"allowOverwriteRoutes"	=>	false,       
			"config"	=>	array(
				"file"	=>	CMS_ROOT."/Modules/blog/config.php"
			),    
			"classes"	=>	array(
				"IndexController"	=>	array(
					"name"	=>	"IndexController",
					"file"	=>	CMS_ROOT."/Modules/blog/controllers/IndexController.php"
				),                                                                       
				"ListController"	=>	array(
					"name"	=>	"ListController",
					"file"	=>	CMS_ROOT."/Modules/blog/controllers/ListController.php"
				),    
				"BlogEntry"	=>	array(
					"name"	=>	"BlogEntry",
					"file"	=>	CMS_ROOT."/Modules/blog/models/BlogEntry.php"
				),   
			),
		),
		"rest"	=>	array(
			"name"	=>	"rest",
			"allowOverwriteRoutes"	=>	true,
			"config"	=>	array(
				"file"	=>	CMS_ROOT."/Modules/rest/config.php"
			),
			"classes"	=>	array(
			),
		)  
	),
);
  
